name: Periodic Functional Tests

on:
  schedule:
    - cron: '*/1 * * * *' # Run every 5 minutes

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        run: echo "hello world";
