name: Periodic Functional Tests

on: [ push, workflow_dispatch ]

jobs:
  run_tests:
    runs-on: self-hosted-osu
    steps:
      # - name: Test command
      #   run: |
      #     echo "hello world"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Execute SSH commmands on remote server 
        run: |
          id
          whoami
          mkdir -p /home/ubuntu/.ssh/
          echo "${{ secrets.SSH_KEY }}" > /home/ubuntu/.ssh/github_actions
          chmod 0600 /home/ubuntu/.ssh/github_actions
      #     ssh -vvv -i /home/runner/.ssh/github_actions -o KexAlgorithms=ecdh-sha2-nistp521 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@130.198.121.194 '/root/k8s-ansible-automation/create-cluster.sh'
      - name: Setup ppc64le k8s cluster
        run: |
          mkdir -p ~/.kube
          scp -i /home/ubuntu/.ssh/github_actions -o MACs=hmac-sha2-256 -o StrictHostKeyChecking=no -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null root@130.198.121.194:/root/.kube/config ~/.kube
          cat ~/.kube/config
      - name: Run Functional Tests
        run: |
          
          log_dir=$(mktemp -d)
          ssh -vvv -i /home/ubuntu/.ssh/github_actions -o KexAlgorithms=ecdh-sha2-nistp521 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@130.198.121.194 'ls -lha'
